### ISSUE TITLE
CodeBuild docker build fails with no basic auth credentials but docker pull works

### ISSUE THREAD

**Issue by larstobi** [awslabs/amazon-ecr-credential-helper#246]
With our /root/.docker/config.json file like this:
`{"credsStore": "ecr-login"}`

`docker build` fails with `no basic auth credentials`. However, when we run `docker pull` on the exact same image, it works just fine.

To me it looks to have similar symptoms to #76.

The `buildspec.yml` we're using:
```
---
version: 0.2

phases:
  install:
    commands:
      # Keep the install until https://github.com/aws/aws-codebuild-docker-images/pull/370
      # is merged and published.
      - PYTHON=python2 /usr/bin/amazon-linux-extras enable docker
      - yum -y install amazon-ecr-credential-helper
      - mkdir -p /root/.docker
      - >
        echo '{"credsStore": "ecr-login"}' > /root/.docker/config.json

  build:
    commands:
      - docker build .
  post_build:
    commands:
      - echo Printing ecr log
      - cat /root/.ecr/log/*
```

The `.ecr/log/` logs:
```
[Container] 2020/11/13 11:03:04 Running command cat /root/.ecr/log/*
time="2020-11-13T11:03:03Z" level=debug msg="Listing credentials"
time="2020-11-13T11:03:03Z" level=debug msg="No credential cache"
time="2020-11-13T11:03:03Z" level=debug msg="Calling ECR.GetAuthorizationToken for default registry"
time="2020-11-13T11:03:03Z" level=debug msg="Saving credentials to file cache" registry=123456789
time="2020-11-13T11:03:03Z" level=debug msg="Retrieving credentials" region=eu-west-1 registry=123456789
 serverURL="https://123456789
.dkr.ecr.eu-west-1.amazonaws.com"
time="2020-11-13T11:03:03Z" level=debug msg="Checking file cache" registry=123456789
time="2020-11-13T11:03:03Z" level=debug msg="Using cached token" registry=123456789
```

CodeBuild image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
Docker 19.03.11
amazon-credentials-helper: 4.0.0
