### ISSUE TITLE
Is there a GitHub Action for this project?

### ISSUE THREAD

**Issue by micahhausler** [awslabs/amazon-ecr-credential-helper#301]
As a GitHub user and AWS user, I'd love to be able to use this project in GitHub actions to authenticate to ECR. 

For example, if I was using the [Docker build/push action](https://github.com/docker/build-push-action) along with [GitHub's IAM OIDC integration](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services), I'd want to be able to authenticate my image pushes/pulls to ECR public and private

cc @samuelkarp

**Comment by micahhausler** [comment]
Ah nevermind, [Docker's login action](https://github.com/docker/login-action#aws-public-elastic-container-registry-ecr) already supports ECR authentication.

**Comment by micahhausler** [comment]
For anyone else interested, here is an example config that worked for me:
```yaml
jobs:
  docker:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      -
        name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@8eba69932f928f2bc1b9837d16a095e7e1cb0845
        with:
          role-to-assume: arn:aws:iam::<account-id>:role/rolename
          aws-region: us-east-1
      -
        name: Login to Public ECR
        uses: docker/login-action@v1
        with:
          registry: public.ecr.aws
        env:
          AWS_REGION: us-east-1
```
