### ISSUE TITLE
Pulling from multiple private registries

### ISSUE THREAD

**Issue by ohmer** [awslabs/amazon-ecr-credential-helper#320]
Hi there,

Not sure if this is a feature or not but here is a use case I have.

Let's say I have multiple registries in a Compose file:

```
service:
  one:
    image: <ACCOUNT_ID_ONE>.dkr.ecr.<REGION_ONE>.amazonaws.com/image_one:tag_one
  two:
    image: <ACCOUNT_ID_TWO>.dkr.ecr.<REGION_TWO>.amazonaws.com/image_two:tag_two
```

`docker compose pull` does not play nicely. The work around I found was to `docker pull` the image ref one by one with a matching `AWS_PROFILE` environment variable set.

`AWS_PROFILE=profile-one docker pull <ACCOUNT_ID_ONE>.dkr.ecr.<REGION_ONE>.amazonaws.com/image_two:tag_one`
`AWS_PROFILE=profile-two docker pull <ACCOUNT_ID_TWO>.dkr.ecr.<REGION_TWO>.amazonaws.com/image_two:tag_two`

Then `docker compose up`.

Am I missing something or some sort of account / profile mapping is needed in this credentials helper?

Cheers!
