### ISSUE TITLE
no basic auth credentials gitlab dind

### ISSUE THREAD

**Issue by punkracy** [awslabs/amazon-ecr-credential-helper#52]
Hi,
I am trying to use amazon ecr credential helper inside gitlab ci job to build and push image to AWS ECR.
When I am using it manually (my machine, gitlab host machine) it works fine. But inside gitlab job using dind (docker in docker) runner it fails. I tried many scenarios for almost week without success. I am not able to provide ~/.ecr/log but I run push with strace. What is interesting is that I do not see reading ~/.aws/config and credentials. But do not know why.

```
Running with gitlab-ci-multi-runner 1.10.1 (1039add)
Using Docker executor with image gitlab/dind:latest ...
Starting service redis:latest ...
Pulling docker image redis:latest ...
Waiting for services to be up and running...
Pulling docker image gitlab/dind:latest ...
Running on runner-64308dd6-project-25-concurrent-0 via gitlab.bitcomp.intra...
Fetching changes...
Removing .m2/
Removing target/
HEAD is now at 54e0ff6 add missing cd
Checking out 54e0ff62 as aws-ecr...
Skipping Git submodules setup
Downloading artifacts for maven-build (8770)...
Downloading artifacts from coordinator... ok        id=8770 responseStatus=200 OK token=9TayDDjr
Checking cache for docker-build/aws-ecr...
Successfully extracted cache
ln: failed to create symbolic link '/sys/fs/cgroup/systemd/name=systemd': Operation not permitted
$ export PATH="~/amazon-ecr-credential-helper/bin/local:$PATH"
$ export BUILD_PATH=`pwd`
$ echo $BUILD_PATH
/builds/bag/geocoding-api
$ which make || ( apt-get update -y && apt-get install build-essential -y )
Ign http://archive.ubuntu.com trusty InRelease
Get:1 http://archive.ubuntu.com trusty-updates InRelease [65.9 kB]
[..install..]
Setting up manpages-dev (3.54-1ubuntu1) ...
Processing triggers for libc-bin (2.19-0ubuntu6.9) ...
$ cd ~/ && git clone https://github.com/awslabs/amazon-ecr-credential-helper.git && cd amazon-ecr-credential-helper && make docker
Cloning into 'amazon-ecr-credential-helper'...
docker run --rm \
	-e TARGET_GOOS= \
	-e TARGET_GOARCH= \
	-v /root/amazon-ecr-credential-helper/bin:/go/src/github.com/awslabs/amazon-ecr-credential-helper/bin \
	sha256:0d269e7f863af6a888849ae346b8ef8e20a7c46dd0e101b87a065d5a35c771f2
. ./scripts/shared_env && ./scripts/build_binary.sh ./bin/local
Built ecr-login
$ mkdir -p ~/.docker/ && echo $ECR_DOCKER_CONFIG > ~/.docker/config.json
$ mkdir -p ~/.aws/ && echo $AWS_CONFIG_FILE > ~/.aws/config && echo $AWS_CREDENTIALS_FILE > ~/.aws/credentials
$ pwd
/root/amazon-ecr-credential-helper
$ echo $PATH
~/amazon-ecr-credential-helper/bin/local:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
$ cd ~/
$ pwd
/root
$ ls -l
total 0
drwxr-xr-x. 6 root root 178 Jul 14 13:33 amazon-ecr-credential-helper
$ cat ~/.docker/config.json
{
 "credsStore": "ecr-login"
 }
$ echo $AWS_CONFIG_FILE
[default]
 output = json
 region = eu-central-1
$ echo $AWS_CREDENTIALS_FILE
[default]
 aws_access_key_id = AKIABLAHBLAH
 aws_secret_access_key = xQxDfxeyzRggn%^&*()BLAHBLAH
$ cd $BUILD_PATH
$ which strace || ( apt-get install strace -y )
Reading package lists...
Building dependency tree...
[..install..]
Setting up strace (4.8-1ubuntu5) ...
$ docker build -t bag/geocoding-api .
Sending build context to Docker daemon 557.1 kB
[..build..]
Successfully built dfe2d3593740
$ docker tag bag/geocoding-api:latest XXXXXXXXXX.dkr.ecr.eu-central-1.amazonaws.com/bag/geocoding-api:latest
$ strace docker push XXXXXXXXXXXX.dkr.ecr.eu-central-1.amazonaws.com/bag/geocoding-api:latest
execve("/usr/bin/docker", ["docker", "push", "XXXXXXXXXXX.dkr.ecr.eu-central-"...], [/* 84 vars */]) = 0
[..cut..]
clock_gettime(CLOCK_REALTIME, {1500039286, 765274400}) = 0
ioctl(2, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, 0xc82005be74) = -1 ENOTTY (Inappropriate ioctl for device)
openat(AT_FDCWD, "/proc/sys/net/core/somaxconn", O_RDONLY|O_CLOEXEC) = 3
[..cut..]
openat(AT_FDCWD, "/dev/urandom", O_RDONLY|O_CLOEXEC) = 3
read(3, "\257\266D\301\24tD\243J\304j\313XZ\262\245\320\200~\367\3\"(\354\27\374skD\330\37\273"..., 4096) = 4096
stat("/usr/lib/libykcs11.so", 0xc82013ad38) = -1 ENOENT (No such file or directory)
stat("/usr/lib64/libykcs11.so", 0xc82013ae08) = -1 ENOENT (No such file or directory)
stat("/usr/lib/x86_64-linux-gnu/libykcs11.so", 0xc82013aed8) = -1 ENOENT (No such file or directory)
stat("/usr/local/lib/libykcs11.so", 0xc82013afa8) = -1 ENOENT (No such file or directory)
stat("/root/.docker/config.json", {st_mode=S_IFREG|0644, st_size=32, ...}) = 0
openat(AT_FDCWD, "/root/.docker/config.json", O_RDONLY|O_CLOEXEC) = 4
read(4, "{\r \"credsStore\": \"ecr-login\"\r }\n", 512) = 32
close(4)                                = 0
[..cut..]
clock_gettime(CLOCK_REALTIME, {1500039286, 825898700}) = 0
write(6, "D\203\1\0\0\1\0\0\0\0\0\0\fXXXXXXXXXX\3dkr\3ec"..., 65) = 65
read(6, 0xc820319000, 512)              = -1 EAGAIN (Resource temporarily unavailable)
[..cut..]
The push refers to a repository [XXXXXXXXXXX.dkr.ecr.eu-central-1.amazonaws.com/bag/geocoding-api]
futex(0x132a030, FUTEX_WAKE, 1)         = 1
read(4, "HTTP/1.1 200 OK\r\nContent-Type: a"..., 4096) = 267
futex(0xc8203c2108, FUTEX_WAKE, 1)      = 1
write(1, "The push refers to a repository "..., 100) = 100
read(4, 0xc8203dc000, 4096)             = -1 EAGAIN (Resource temporarily unavailable)
futex(0x132aca8, FUTEX_WAIT, 0, NULLd98ad87e07f6: Preparing
ce8f2ebb2511: Preparing
b0f743408169: Preparing
5bef08742407: Preparing
no basic auth credentials
```

My gitlab job look like this

```
docker-build:
  stage: package
  script:
  - export BUILD_PATH=`pwd`
  - echo $BUILD_PATH
  - 'which make || ( apt-get update -y && apt-get install build-essential -y )'
  - cd ~/ && git clone https://github.com/awslabs/amazon-ecr-credential-helper.git && cd amazon-ecr-credential-helper && make docker
  - mkdir -p ~/.docker/ && echo $ECR_DOCKER_CONFIG > ~/.docker/config.json
  - mkdir -p ~/.aws/ && echo $AWS_CONFIG_FILE > ~/.aws/config && echo $AWS_CREDENTIALS_FILE > ~/.aws/credentials
  - pwd
  - echo $PATH
  - cd ~/
  - pwd
  - ls -l
  - cat ~/.docker/config.json
  - echo $AWS_CONFIG_FILE
  - echo $AWS_CREDENTIALS_FILE
  - cd $BUILD_PATH 
  - 'which strace || ( apt-get install strace -y )'
  - docker build -t bag/geocoding-api .
  - docker tag bag/geocoding-api:latest XXXXXXXXX.dkr.ecr.eu-central-1.amazonaws.com/bag/geocoding-api:latest
  - strace docker push XXXXXXXX.dkr.ecr.eu-central-1.amazonaws.com/bag/geocoding-api:latest
```

I tired with $AWS_ACCESS_KEY_ID and $AWS_SECRET_ACCESS_KEY and it is the same issue.

Thanks in advance for any tip.

**Comment by piu28** [comment]
I was facing the similar issue with Jenkins. From CLI, I was able to pull without login command but from Jenkins I was getting error "no basic auth credentials". 

I added the "docker-credential-ecr-login" executable file in the path /usr/bin/, and its working fine now. I am able to pull and push ECR Repo from Jenkins without Login.

**Comment by punkracy** [comment]
Thanks, I will try that out.

**Comment by guikcd** [comment]
The issue is that docker 17.06.0-ce depreciate (See https://docs.docker.com/release-notes/docker-ce/#17060-ce-2017-06-28)  the -e (email) flag and aws ecr get-login generate it by default:

```
$ aws ecr get-login
docker login -u AWS -p <token> -e none https://167012524447.dkr.ecr.eu-west-1.amazonaws.com
```

New awscli option `--no-include-email` disable -e flag generation (https://github.com/aws/aws-cli/blob/develop/CHANGELOG.rst#11191) :

```
$ aws ecr get-login --no-include-email
docker login -u AWS -p <token> https://167012524447.dkr.ecr.eu-west-1.amazonaws.com
```

**Comment by samuelkarp** [comment]
@punkracy The strace output isn't particularly useful as I can't see whether the credential helper is getting invoked.  The best way to troubleshoot this is going to be to look at the credential helper's logs and see what's going wrong there (or, if nothing is there, you know that it isn't being invoked).

**Comment by punkracy** [comment]
@samuelkarp sorry for lack of response. Solution by @piu28 worked for me (although I try now to build my dind image with a helper). So we can close issue (sorry for delay).
The problem with gitlab and docker here was in the way that images are prepared for next steps. So coping compiled utility to /usr/bin did the trick (because it is available also in next steps). So setting PATH was not useful here.

**Comment by samuelkarp** [comment]
@punkracy Glad it worked, thanks for confirming!

**Comment by aPoCoMiLogin** [comment]
@piu28 just saved my life.

**Comment by lavinia09** [comment]
I'm struggling with the same problem. 
Where did you add 'docker-credential-ecr-login'? In the .gitlab-ci.yml? Or in the pipeline settings?

**Comment by punkracy** [comment]
You do not specify executable anywhere. When you issue "docker" command like: docker push it try to authenticate based on ~/.docker/config.json. And there should be 
```
{
 "credsStore": "ecr-login"
 }
```
And it will look for docker-credential-CONFIG_ENTRY, so docker-credential-ecr-login.

Right now we're not using this project, we wrote our own helper in Go, but it was helpful for start.

**Comment by rbudiharso** [comment]
what kind of changes do you put to create the custom image? is it into docker:dind or docker:stable image?

**Comment by punkracy** [comment]
You referring to creating docker image or creating own helper?

**Comment by rbudiharso** [comment]
> So coping compiled utility to /usr/bin did the trick (because it is available also in next steps)
I'm referring to this, I assume you build a custom image which include the docker-credential-ecr-login built in.

**Comment by punkracy** [comment]
Yes. Back then we build our own `dind-aws-ecr:latest` with gitlab and it looked something like this
```
tools-build:
  image: docker
  services:
  - docker:dind
  stage: build
  script:
    - echo "ENV AWS_ACCESS_KEY_ID $AWS_ACCESS_KEY_ID" >> Dockerfile
    - echo "ENV AWS_SECRET_ACCESS_KEY $AWS_SECRET_ACCESS_KEY" >> Dockerfile
    - echo "ENV AWS_REGION eu-central-1" >> Dockerfile
    - mkdir ~/.docker
    - cp config.json ~/.docker
    - cp docker-credential-ecr /usr/bin
    - docker build -t images.company.com/blah/dind-aws-ecr:latest .
ecr:latest
    - docker push images.company.com/blah/dind-aws-ecr:latest

```
Of course config.json was a part of the project and `docker-credential-ecr` was build in previous step
