### ISSUE TITLE
Unable to pull images when using kubelet.config.k8s.io/v1

### ISSUE THREAD

**Issue by dntosas** [awslabs/amazon-ecr-credential-helper#616]
Hey team 👋 

Trying to make a k8s cluster v1.27 work with Kubelet alongside with ecr-creds-helper following this guide https://kubernetes.io/docs/tasks/administer-cluster/kubelet-credential-provider/

This is my configuration:
```
apiVersion: kubelet.config.k8s.io/v1beta1
kind: CredentialProviderConfig
providers:
  - name: docker-credential-ecr-login
    matchImages:
      - "*.dkr.ecr.*.amazonaws.com"
      - "public.ecr.aws"
    defaultCacheDuration: "12h"
    apiVersion: credentialprovider.kubelet.k8s.io/v1beta1
```

Getting always this error, tried multiple configs/args etc. Any clues?

Error:
```
level=error msg="Error parsing the serverURL" error="parse \"https://{\\\"kind\\\":\\\"CredentialProviderRequest\\\",\\\"apiVersion\\\":\\\"credentialprovider.kubelet.k8s.io/v1beta1\\\",\\\"image\\\":\\\"XXXX.dkr.ecr.eu-west-1.amazonaws.com/XXXX\\\"}\": invalid port \":\\\"credentialprovider.kubelet.k8s.io\" after host" serverURL="{\"kind\":\"CredentialProviderRequest\",\"apiVersion\":\"credentialprovider.kubelet.k8s.io/v1beta1\",\"image\":\"XXX.dkr.ecr.eu-west-1.amazonaws.com/XXX\"}"
```
