### ISSUE TITLE
I am able to run an image from ***.amazonaws.com/image:latest but unable to run an almost identical image ***.amazonaws.com/image:<custom_tag>

### ISSUE THREAD

**Issue by dnk8n** [awslabs/amazon-ecr-credential-helper#83]
Hi, 

Unsure if this is the correct place for this issue. Please advise.

From ECS I get error: `STOPPED (CannotStartContainerError: API error (500): driver)` when using ecs-cli compose. The configuration is:

```
  logspout:
      image: ***.amazonaws.com/logspout:poc
      hostname: logspout
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock
      environment:
        - ROUTE_URIS=logstash+udp://logstash-for-logspout:5959
      links:
        - logstash-for-logspout
  logstash-for-logspout:
      image: ***.amazonaws.com/logstash_for_logspout:poc
      hostname: logstash-for-logspout
      ports:
        - 5959:5959/udp
```

From the relevant container instances, when I run `docker run --net=ec2user_default -it ***.amazonaws.com/logspout:latest`, everything works fine.

But `docker run --net=ec2user_default -it ***.amazonaws.com/logspout:poc` fails with

```
Unable to find image '***.amazonaws.com/opendna-logstash-cluster-logspout:poc' locally
docker: Error response from daemon: Get https://***.amazonaws.com/v2/logspout/manifests/poc: no basic auth credentials.
```

In other scenarios of running a tagged (e.g. poc) image, it works correctly. The problem seems to be that the image is not visible locally like the others are. How could that be? Is there a command to sync in the images from our ecr repositories?

Any help would be greatly appreciated.
