### ISSUE TITLE
[Feature Request] Add support for ECR Pull Through Cache registry map

### ISSUE THREAD

**Issue by rblaine95** [awslabs/amazon-ecr-credential-helper#947]
### The Problem

The ECR credential helper currently only supports authentication for native ECR registries. However, when using ECR Pull Through Cache feature for external registries (like `docker.io`, `ghcr.io`, etc), the credential helper doesn't recognize these as valid ECR endpoints requiring authentication.

### Current setup

I have configured a Pull Through Cache in ECR for docker.io images, with `containerd` configured to use it:
```toml
# /etc/containerd/certs.d/docker.io/hosts.toml
server = "https://402177810328.dkr.ecr.af-south-1.amazonaws.com/v2/docker-hub"

[host."https://402177810328.dkr.ecr.af-south-1.amazonaws.com/v2/docker-hub"]
  capabilities = ["pull", "resolve"]
  override_path = true
```

The registry redirection works perfectly, but authentication fails because the credential helper doesn't recognize this as a valid ECR endpoint.

If I exec onto a running EKS worker and run:
```bash
crictl pull \
  --creds "AWS:$(aws ecr get-login-password --region af-south-1)" \
  docker.io/debian:12
```

Then the image pulls through the ECR cache perfectly.

### Related Discussion

Please feel free to see a lengthy discussion and investigation into this here https://github.com/containerd/containerd/discussions/11385

### Proposed solution

Add support for a registry mapping configuration file (e.g., `custom.json`) that maps external registries to their corresponding ECR Pull Through Cache endpoints:
```json
{
  "docker.io": "402177810328.dkr.ecr.af-south-1.amazonaws.com",
  "ghcr.io": "402177810328.dkr.ecr.af-south-1.amazonaws.com"
}
```

When the credential helper receives an authentication request for a registry (e.g., `docker.io`), it would:

1. Check if the registry exists in the mapping file
2. If found, use the corresponding ECR endpoint for authentication
3. Generate credentials using the standard ECR authentication flow

### Benefits
* Seamless authentication when using ECR Pull Through Cache
* Consistent credential management across both native ECR and Pull Through Cache registries
* No need for separate credential handling for cached external registries
* Improved developer experience when working with ECR Pull Through Cache
